env:
    MANIFEST: https://github.com/RisingTechOSS/android -b thirteen --git-lfs
    DEVICE: RMX1901
    OEM: realme
    LOCAL_MANIFEST: https://github.com/ij-israfil/local_manifest.git
    TARGET: bacon
    LUNCH_COMBO: lineage_${DEVICE}-userdebug
    OUTPUT: r*.zip
    CLO: RMX1901:AppDrive
    CLO_1: ENCRYPTED[!11AUUJTUA047eUQaxBiT6H_HKoFZRJHjV2qmvfZGTZxGo19hdu2UXhhFQYZJu1vXKKEDLA3MYZGE6yyOOG!]
    URI: https://sourceforge.net/projects/rom-13/files/Caches/Rising/ccache.tar.gz/download
    ROM_U: 1
    
task:
  name: "build"
  timeout_in: 120m
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
