env:
    MANIFEST: https://github.com/ArrowOS/android_manifest.git  -b arrow-11.0
    DEVICE: X01BD
    OEM: asus
    LOCAL_MANIFEST: https://github.com/ManitnjG/local_manifest.git
    TARGET: bacon
    LUNCH_COMBO: arrow_${DEVICE}-userdebug
    OUTPUT: A*.zip
    CLO: 1:X01BD
    CLO_1: ENCRYPTED[!6d46377e4d6368361243b62bf40bc2cdb7e6cf1f7358140a1448ff3b6faebba771dfb38fffe23fee0e2132be791b77ff!]
    URI: https://sourceforge.net/projects/manig-x01bd/files/ccache.tar.gz/download
    ROM_U: 1
    
task:
  name: "build"
  timeout_in: 120m
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
