env:
    MANIFEST: https://github.com/Havoc-OS/android_manifest.git -b thirteen --git-lfs
    DEVICE: RMX1901
    OEM: realme
    LOCAL_MANIFEST: https://github.com/Shravan55555/local_manifest-1.git
    TARGET: bacon
    LUNCH_COMBO: lineage_${DEVICE}-userdebug
    OUTPUT: H*.zip
    CLO: RMX1901:AppDrive
    CLO_1: ENCRYPTED[!16f68dd6cd6c746bb67a5d6bdf9b7027db69de8332aa9606f676cff8a20e5990b0d32851a42603b3c26242982572ad36!]
    URI: https://sourceforge.net/projects/realme-x-1901/files/ccache/Havoc/ccache.tar.gz/download
    ROM_U: 1
    
task:
  name: "build"
  timeout_in: 120m
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
