env:
    MANIFEST: https://github.com/Havoc-OS/android_manifest.git -b thirteen --git-lfs
    DEVICE: RMX1901
    OEM: realme
    LOCAL_MANIFEST: https://github.com/Shravan55555/local_manifest-1.git
    TARGET: bacon
    LUNCH_COMBO: lineage_${DEVICE}-userdebug
    OUTPUT: H*.zip
    CLO: RMX1901
    CLO_1: ENCRYPTED[!bc1e6bb3689e58441c8abedee261e86a68a43950b30574a7e5452078292d6f50e7afd6d84f9c00a6a71be4de4c53923a!]
    URI: example.com
    ROM_U: 0
    
task:
  name: "build"
  timeout_in: 120m
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
