env:
    MANIFEST: https://github.com/Evolution-X/manifest -b tiramisu --git-lfs
    DEVICE: RMX1901
    OEM: realme
    LOCAL_MANIFEST: https://github.com/ij-israfil/local_manifest.git
    TARGET: bacon
    LUNCH_COMBO: evolution_RMX1901-userdebug
    mka evolution
    OUTPUT: r*.zip
    CLO: RMX1901:AppDrive
    CLO_1: ENCRYPTED[!16f68dd6cd6c746bb67a5d6bdf9b7027db69de8332aa9606f676cff8a20e5990b0d32851a42603b3c26242982572ad36!]
    URI: 
    ROM_U: 1
    
task:
  name: "build"
  timeout_in: 120m
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
