env:
    MANIFEST: https://github.com/PixelExtended/manifest -b thunder
    DEVICE: RMX1901
    OEM: realme
    LOCAL_MANIFEST: https://github.com/Shravan55555/local_manifest-1.git
    TARGET: bacon
    LUNCH_COMBO: aosp_${DEVICE}-userdebug
    OUTPUT: P*.zip
    CLO: RMX1901:AppDrive
    CLO_1: ENCRYPTED[!9307771b67b93b458d68c3302aa66582f9574e18ba0f8c6eba8ecf5f2db99ac5f3819eea3eee5c09c71d99a9c6f06054!]
    URI: https://sourceforge.net/projects/realme-x-1901/files/ccache/Pex/ccache.tar.gz/download
    ROM_U: 1
    
task:
  name: "build"
  timeout_in: 120m
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
