env:
    MANIFEST: https://github.com/Havoc-OS/android_manifest.git -b thirteen --git-lfs
    DEVICE: RMX1901
    OEM: realme
    LOCAL_MANIFEST: https://github.com/Shravan55555/local_manifest-1.git
    TARGET: bacon
    LUNCH_COMBO: lineage_${DEVICE}-userdebug
    OUTPUT: H*.zip
    CLO: RMX1901
    CLO_1: ENCRYPTED[!c35442f7f68f714ce56be6c24e86c104f368fb925d77fa70d2b3637e1a7879478029642c0e9d964a2769ed725e122ae5!]
    URI: example.com
    ROM_U: 0
    
task:
  name: "build"
  timeout_in: 120m
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
