#!/bin/bash
cd ~/rom
export CCACHE_DIR=/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 100G
ccache -o compression=true
ccache -z
. build/envsetup.sh
lunch "$LUNCH_COMBO"
mka $TARGET -j8
